config: toy_model_config.yaml
model:
  family: gpt2
  n_dims: 5
  n_embd: 64
  n_head: 2
  n_layer: 3
  n_positions: 101
out_dir: ./models
test_run: false
training:
  batch_size: 32
  curriculum:
    dims:
      end: 5
      inc: 1
      interval: 10000
      start: 1
    points:
      end: 10
      inc: 1
      interval: 10000
      start: 5
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: linear_regression
  task_kwargs: {}
  train_steps: 500001
wandb:
  entity: marcomolinari4
  log_every_steps: 100
  name: null
  notes: ''
  project: train toy regressor
